---
- name: Launch EC2 instance
  amazon.aws.ec2_instance:
    name: "{{ tag_name }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ ami_id }}"
    region: "{{ region }}"
    key_name: "{{ keypair }}"
    security_group: "{{ sg_name }}"
    instance_profile_name: "{{ instance_profile_name }}"
    wait: yes
  register: ec2_output
